---
- name: RedHat - Add Elasticsearch repository key
  rpm_key:
    key: "{{ kibana_gpgkey_url }}"
    state: "present"

- name: RedHat - Add kibana repository
  template: src=kibana.repo dest=/etc/yum.repos.d/kibana-{{ kibana_major_version }}.repo

- name: RedHat - Install Kibana
  yum: name=kibana{% if kibana_version is defined and kibana_version != ""  %}-{{ kibana_version }}{% endif %} state=present update_cache=yes
  register: redhat_kibana_install_from_repo
  until: '"failed" not in redhat_kibana_install_from_repo'
  retries: 5
  delay: 10
